export const productos = [
  {
    id: 1,
    tipo: "Anillos",
    nombre: "Ajustable Antiestres",
    descripcion: "Ajustable Antiestres",
    costo: 3690,
    cantidad: 2,
    total: 7380,
    precio: 8990,
    "precio net": 13990,
  },
  {
    id: 2,
    tipo: "Anillos",
    nombre: "Ajustable Patita",
    descripcion: "Ajustable Patita",
    costo: 4590,
    cantidad: 2,
    total: 9180,
    precio: 13990,
    "precio net": 25990,
  },
  {
    id: 3,
    tipo: "Aritos",
    nombre: "Trepador Mariposa",
    descripcion: "Trepador Mariposa",
    costo: 3590,
    cantidad: 1,
    total: 3590,
    precio: 8600,
    "precio net": 11800,
  },
  {
    id: 4,
    tipo: "Aritos",
    nombre: "Trepador Hojas Brillo",
    descripcion: "Trepador Hojas Brillo",
    costo: 4290,
    cantidad: 1,
    total: 4290,
    precio: 9900,
    "precio net": 13700,
  },
  {
    id: 5,
    tipo: "Aritos",
    nombre: "Trepador Brillo",
    descripcion: "Trepador Brillo",
    costo: 3490,
    cantidad: 1,
    total: 3490,
    precio: 8200,
    "precio net": 11200,
  },
  {
    id: 6,
    tipo: "Aritos",
    nombre: "Sol & Luna",
    descripcion: "Sol & Luna",
    costo: 3590,
    cantidad: 1,
    total: 3590,
    precio: 8600,
    "precio net": 11800,
  },
  {
    id: 7,
    tipo: "Aritos",
    nombre: "Cuadrado Nudo",
    descripcion: "Cuadrado Nudo",
    costo: 2590,
    cantidad: 1,
    total: 2590,
    precio: 6200,
    "precio net": 8300,
  },
  {
    id: 8,
    tipo: "Aritos",
    nombre: "Circon Ovalados Brillantes",
    descripcion: "Circon Ovalados Brillantes",
    costo: 5590,
    cantidad: 1,
    total: 5590,
    precio: 11990,
    "precio net": 0,
  },
  {
    id: 9,
    tipo: "Aritos",
    nombre: "Circon Redondo",
    descripcion: "Circon Redondo",
    costo: 1990,
    cantidad: 2,
    total: 3980,
    precio: 4600,
    "precio net": 5700,
  },
  {
    id: 10,
    tipo: "Aritos",
    nombre: "Corazon Te Quiero",
    descripcion: "Corazon Te Quiero",
    costo: 3590,
    cantidad: 1,
    total: 3590,
    precio: 8400,
    "precio net": 11500,
  },
  {
    id: 11,
    tipo: "Aritos",
    nombre: "Cuadrado Brillante",
    descripcion: "Cuadrado Brillante",
    costo: 2490,
    cantidad: 1,
    total: 2490,
    precio: 5900,
    "precio net": 8000,
  },
  {
    id: 12,
    tipo: "Brasaletes",
    nombre: "Pandora Mickey",
    descripcion: "Pandora Mickey",
    costo: 15990,
    cantidad: 1,
    total: 15990,
    precio: 39990,
    "precio net": 0,
  },
  {
    id: 13,
    tipo: "Brasaletes",
    nombre: "Pandora Princesa",
    descripcion: "Pandora Princesa",
    costo: 15990,
    cantidad: 1,
    total: 15990,
    precio: 39990,
    "precio net": 0,
  },
  {
    id: 14,
    tipo: "Cadenas",
    nombre: "Pelotas 45cm",
    descripcion: "Pelotas 45cm",
    costo: 4590,
    cantidad: 1,
    total: 4590,
    precio: 10900,
    "precio net": 14700,
  },
  {
    id: 15,
    tipo: "Cadenas",
    nombre: "Turbillon 40cm",
    descripcion: "Turbillon 40cm",
    costo: 6590,
    cantidad: 1,
    total: 6590,
    precio: 15800,
    "precio net": 21500,
  },
  {
    id: 16,
    tipo: "Cadenas",
    nombre: "Corazones 50cm",
    descripcion: "Corazones 50cm",
    costo: 5990,
    cantidad: 1,
    total: 5990,
    precio: 14500,
    "precio net": 19200,
  },
  {
    id: 17,
    tipo: "Cadenas",
    nombre: "Caracol 45cm",
    descripcion: "Caracol 45cm",
    costo: 6590,
    cantidad: 1,
    total: 6590,
    precio: 15800,
    "precio net": 21500,
  },
  {
    id: 18,
    tipo: "Cadenas",
    nombre: "Argolla 40cm",
    descripcion: "Argolla 40cm",
    costo: 6590,
    cantidad: 1,
    total: 6590,
    precio: 15800,
    "precio net": 21500,
  },
  {
    id: 19,
    tipo: "Cadenas",
    nombre: "Cadena Turbillon 50cm(MIO)",
    descripcion: "Cadena Turbillon 50cm(MIO)",
    costo: 16990,
    cantidad: 1,
    total: 16990,
    precio: 0,
    "precio net": 0,
  },
  {
    id: 20,
    tipo: "Charms",
    nombre: "Corazon Love",
    descripcion: "Corazon Love",
    costo: 4990,
    cantidad: 1,
    total: 4990,
    precio: 12400,
    "precio net": 19200,
  },
  {
    id: 21,
    tipo: "Charms",
    nombre: "Corazon Medieval",
    descripcion: "Corazon Medieval",
    costo: 5990,
    cantidad: 1,
    total: 5990,
    precio: 14500,
    "precio net": 19200,
  },
  {
    id: 22,
    tipo: "Charms",
    nombre: "Harry Potter",
    descripcion: "Harry Potter",
    costo: 6590,
    cantidad: 1,
    total: 6590,
    precio: 16500,
    "precio net": 21100,
  },
  {
    id: 23,
    tipo: "colgantes",
    nombre: "Nudo",
    descripcion: "Nudo",
    costo: 1990,
    cantidad: 1,
    total: 1990,
    precio: 4900,
    "precio net": 6400,
  },
  {
    id: 24,
    tipo: "colgantes",
    nombre: "Esfera Strass",
    descripcion: "Esfera Strass",
    costo: 1990,
    cantidad: 1,
    total: 1990,
    precio: 4900,
    "precio net": 6400,
  },
  {
    id: 27,
    tipo: "Pulseras",
    nombre: "Pelotas",
    descripcion: "Pelotas",
    costo: 3290,
    cantidad: 1,
    total: 3290,
    precio: 6200,
    "precio net": 0,
  },
  {
    id: 28,
    tipo: "Pulseras",
    nombre: "Corazones",
    descripcion: "Corazones",
    costo: 2990,
    cantidad: 1,
    total: 2990,
    precio: 5200,
    "precio net": 5900,
  },
  {
    id: 29,
    tipo: "Pulseras",
    nombre: "Infantil Rombo (MIO)",
    descripcion: "Infantil Rombo (MIO)",
    costo: 2590,
    cantidad: 1,
    total: 2590,
    precio: 0,
    "precio net": 0,
  },
  {
    id: 30,
    tipo: "Anillos",
    nombre: "Conchas Esferas",
    descripcion: "Conchas Esferas",
    costo: 3990,
    cantidad: 1,
    total: 3990,
    precio: 8990,
    "precio net": 18000,
  },
  {
    id: 31,
    tipo: "Anillos",
    nombre: "Cintillo Circones Granate Negro ",
    descripcion: "Cintillo Circones Granate Negro ",
    costo: 4590,
    cantidad: 1,
    total: 4590,
    precio: 9900,
    "precio net": 14700,
  },
  {
    id: 32,
    tipo: "Anillos",
    nombre: "Circones morado blanco",
    descripcion: "Circones morado blanco",
    costo: 3690,
    cantidad: 1,
    total: 3690,
    precio: 8100,
    "precio net": 20800,
  },
  {
    id: 33,
    tipo: "Anillos",
    nombre: "Cintillo Circones Cuadrados",
    descripcion: "Cintillo Circones Cuadrados",
    costo: 4990,
    cantidad: 1,
    total: 4990,
    precio: 9900,
    "precio net": 19200,
  },
  {
    id: 34,
    tipo: "Pulseras",
    nombre: "Corazones Entrelazados",
    descripcion: "Corazones Entrelazados",
    costo: 1990,
    cantidad: 1,
    total: 1990,
    precio: 3990,
    "precio net": 6000,
  },
  {
    id: 35,
    tipo: "Pulseras",
    nombre: "Tradicional con Ovalos",
    descripcion: "Tradicional con Ovalos",
    costo: 2990,
    cantidad: 1,
    total: 2990,
    precio: 6100,
    "precio net": 9600,
  },
  {
    id: 36,
    tipo: "Pulseras",
    nombre: "Rombo Flor",
    descripcion: "Rombo Flor",
    costo: 2590,
    cantidad: 1,
    total: 2590,
    precio: 5600,
    "precio net": 7300,
  },
  {
    id: 37,
    tipo: "Aritos",
    nombre: "Trepador Patitas",
    descripcion: "Trepador Patitas",
    costo: 4590,
    cantidad: 1,
    total: 4590,
    precio: 9990,
    "precio net": 12900,
  },
  {
    id: 38,
    tipo: "Aritos",
    nombre: "Trepador Circones",
    descripcion: "Trepador Circones",
    costo: 4590,
    cantidad: 1,
    total: 4590,
    precio: 9990,
    "precio net": 16000,
  },
  {
    id: 39,
    tipo: "Aritos",
    nombre: "Trepador Seis Estrellas",
    descripcion: "Trepador Seis Estrellas",
    costo: 2990,
    cantidad: 1,
    total: 2990,
    precio: 6190,
    "precio net": 22900,
  },
  {
    id: 40,
    tipo: "Aritos",
    nombre: "Trepador Tres Estrellas Circon",
    descripcion: "Trepador Tres Estrellas Circon",
    costo: 4590,
    cantidad: 1,
    total: 4590,
    precio: 9990,
    "precio net": 16990,
  },
  {
    id: 41,
    tipo: "Aritos",
    nombre: "AritosBidu con Cadena ",
    descripcion: "AritosBidu con Cadena ",
    costo: 3990,
    cantidad: 1,
    total: 3990,
    precio: 8890,
    "precio net": 11200,
  },
  {
    id: 42,
    tipo: "Aritos",
    nombre: "Pasador Nudo de Bruja",
    descripcion: "Pasador Nudo de Bruja",
    costo: 3990,
    cantidad: 1,
    total: 3990,
    precio: 8890,
    "precio net": 12800,
  },
  {
    id: 43,
    tipo: "Aritos",
    nombre: "Circon Tornasol Cuadrado 4x4",
    descripcion: "Circon Tornasol Cuadrado 4x4",
    costo: 1690,
    cantidad: 1,
    total: 1690,
    precio: 3900,
    "precio net": 5400,
  },
  {
    id: 44,
    tipo: "Aritos",
    nombre: "Estrella Circon Blanca 4mm",
    descripcion: "Estrella Circon Blanca 4mm",
    costo: 1690,
    cantidad: 1,
    total: 1690,
    precio: 3590,
    "precio net": 5400,
  },
  {
    id: 45,
    tipo: "Aritos",
    nombre: "Estrella Circon Rosa 6mm",
    descripcion: "Estrella Circon Rosa 6mm",
    costo: 1890,
    cantidad: 1,
    total: 1890,
    precio: 4990,
    "precio net": 6000,
  },
  {
    id: 46,
    tipo: "Aritos",
    nombre: "Circon 8mm",
    descripcion: "Circon 8mm",
    costo: 2290,
    cantidad: 1,
    total: 2290,
    precio: 4990,
    "precio net": 7300,
  },
  {
    id: 47,
    tipo: "Aritos",
    nombre: "Estrella",
    descripcion: "Estrella",
    costo: 2990,
    cantidad: 1,
    total: 2990,
    precio: 6190,
    "precio net": 10500,
  },
  {
    id: 48,
    tipo: "Aritos",
    nombre: "Patita Negra",
    descripcion: "Patita Negra",
    costo: 3690,
    cantidad: 1,
    total: 3690,
    precio: 8190,
    "precio net": 12990,
  },
  {
    id: 49,
    tipo: "Aritos",
    nombre: "Cuadrado Micro Circon",
    descripcion: "Cuadrado Micro Circon",
    costo: 3890,
    cantidad: 1,
    total: 3890,
    precio: 8790,
    "precio net": 7100,
  },
  {
    id: 50,
    tipo: "Aritos",
    nombre: "Aritoscorazon (del Tripack)",
    descripcion: "Aritoscorazon (del Tripack)",
    costo: 5590,
    cantidad: 1,
    total: 5590,
    precio: 3990,
    "precio net": 0,
  },
  {
    id: 51,
    tipo: "Tripack",
    nombre: "flores (tripack)",
    descripcion: "flores (tripack)",
    costo: 5590,
    cantidad: 1,
    total: 5590,
    precio: 5990,
    "precio net": 0,
  },
  {
    id: 52,
    tipo: "Anillos",
    nombre: "Anillo  cintillo circon ",
    descripcion: 6990,
    costo: "$6.990",
    cantidad: 0,
    total: 12990,
    precio: "8990",
    "precio net": 0,
  },
];
